import { TExperience } from "./types";

export const experiences: TExperience[] = [
    {
        position: "Full Stack Developer",
        company: "LeasePlan",
        url: "https://www.leaseplan.com",
        description:
            "One of the world's leading leasing companies, with 1.7 million vehicles in over 30 countries.",
        date: "08/2019 - present",
        achievements: [
            "Owned, coordinated, and delivered a valuable MVP business solution for fleet management of LP France within tight deadlines",
            "Migrated teams to new cloud architecture as part of the ops and frontend quality team",
            "Improved shared pipeline templates as part of the ops and frontend quality team",
            "Created internal analytics tools to improve technical management's oversight over various projects",
            "Significantly improved and scaled to dozens of teams internal shared backend-for-frontend solution",
            "Revamped and scaled the integration of in-house sitecore form-library solution",
            "Created an in-house vulnerability scanning solution to improve vulnerability audits' efficiency",
            "Hands-on mentored dozens of engineers",
            "Enhanced front-end architecture and build tools",
        ],
        stack: [
            "auth0-react",
            "axios",
            "babel",
            "bash",
            "bem",
            "cypress",
            "datadog",
            "docker",
            "enzyme",
            "eslint",
            "express",
            "gitlab",
            "html5",
            "javascript",
            "jest",
            "k8s",
            "koa",
            "lodash",
            "material-ui",
            "mocha",
            "moment",
            "msw",
            "node",
            "prettier",
            "python",
            "react",
            "react-final-form",
            "react-i18next",
            "react-router",
            "redux",
            "redux-saga",
            "reselect",
            "rollup",
            "scss",
            "shell",
            "sitecore",
            "sitecore-jss",
            "sitecore-jss-react",
            "standard-version",
            "storybook",
            "styled-components",
            "superagent",
            "testing-library",
            "tslint",
            "typescript",
            "webpack",
        ],
    },
    {
        position: "Senior Frontend Developer",
        company: "Catawiki",
        url: "https://www.catawiki.com",
        description: "Europe's fastest growing online auction house",
        date: "02/2019 - 07/2019",
        achievements: [
            "Contributed to the development and launch of a mobile-first auction lot details page",
            "Enhanced build tools to streamline the development process",
            "Refined frontend architecture for improved performance, maintainability, and scalability",
        ],
        stack: [
            "ansible",
            "babel",
            "bem",
            "docker",
            "eslint",
            "express",
            "html5",
            "javascript",
            "node",
            "phoenix-css",
            "react",
            "redux",
            "redux-thunk",
            "scss",
            "shell",
            "tslint",
            "typescript",
            "webpack",
        ],
    },
    {
        position: "Senior Frontend Developer",
        company: "IPsoft",
        url: "https://amelia.ai/aiops/",
        description:
            "Enterprise-scale autonomic and cognitive solutions platform, in use by 1 in 10 Fortune 1000 companies",
        date: "09/2017 - 11/2018",
        achievements: [
            "Migrated Single-Page Application (SPA) from a monolith into a monorepo architecture, which enabled better code isolation, reusability, and maintenance across different services.",
            "Migrated SPA from ExtJS 4 to React 16 ecosystem, which improved the application's performance, maintainability, and scalability.",
            "Initiated and guided code style and architecture unification, which led to consistent code quality, better collaboration, and reduced technical debt.",
            "Introduced build tools to increase team efficiency and code quality. For instance, reducing the time to first meaningful paint on all modules from 16s to 200ms, which improved the user experience.",
            "Improved frontend architecture for better performance, maintainability, and scalability.",
        ],
        stack: [
            "angular",
            "babel",
            "bem",
            "d3",
            "docker",
            "eslint",
            "express",
            "extjs4",
            "haproxy",
            "html5",
            "javascript",
            "maven",
            "node",
            "react",
            "redux",
            "redux-saga",
            "scss",
            "semantic-ui",
            "thymeleaf",
            "webpack",
            "xml",
            "xslt",
        ],
    },
    {
        position: "Frontend Developer",
        company: "Casengo",
        description: "Customer support platform",
        url: "https://www.casengo.com",
        date: "06/2015 - 08/2017",
        achievements: [
            "Created a revenue-generating messenger bot from scratch, driving business growth",
            "Reduced technical debt, making future development and maintenance more efficient",
            "Enhanced the application's performance and stability, providing a better user experience",
            "Implemented scalable UI solutions, allowing the app to grow seamlessly",
            "Adapted the application for tablets and smartphones, reaching a wider audience",
            "Streamlined CSS using the BEM methodology, improving collaboration and maintainability",
            "Facilitated the unification of business logic knowledge, increasing team efficiency",
        ],
        stack: [
            "angular",
            "atmosphere",
            "babel",
            "bem",
            "bootstrap",
            "eslint",
            "express",
            "extjs",
            "html5",
            "javascript",
            "mongodb",
            "mongoose",
            "node",
            "scss",
            "socket-io",
            "webpack",
        ],
    },
    {
        position: "Frontend Developer",
        company: "Mail.Ru Group",
        url: "https://mail.ru",
        description:
            "Biggest russian e-mail service, 100mln accounts, 43.2 million active users/month",
        date: "08/2014 - 05/2015",
        achievements: [
            "Assisted in designing and implementing a 2-step-authentication integration for improved security",
            "Designed, implemented, and integrated a user-friendly password recovery interface",
            "Integrated emoji support into email lists and compose views for enhanced user engagement",
            "Developed and integrated enhanced beta-testing functionality for end users, improving product quality",
            "Contributed to the unification of an in-house cross-project component toolkit, increasing collaboration efficiency",
        ],
        stack: [
            "bem-toolkit",
            "css3",
            "grunt",
            "html5",
            "javascript",
            "jquery",
            "jssdk",
            "require",
            "scss",
            "xml",
        ],
    },
    {
        position: "Frontend Developer",
        company: "Self-employed",
        description: "Freelancing projects",
        url: "",
        date: "04/2014 - 08/2014",
        achievements: [
            "Successfully completed various CSS, HTML, and jQuery freelance projects, delivering customized frontend solutions for diverse clients",
        ],
        stack: ["css", "html", "javascript", "jquery"],
    },
    {
        position: "Frontend Developer",
        company: "AdProfy",
        description: "Advertising platform",
        url: "http://adprofy.com",
        date: "04/2012 - 04/2014",
        achievements: [
            "Developed and optimized the main advertising platform's frontend, enhancing user experience and visual appeal",
            "Designed and implemented responsive targeted landing pages for various audience segments, improving user engagement and conversion rates",
            "Collaborated with UI/UX designers and backend developers to ensure seamless integration of design elements and functionality",
            "Conducted thorough testing and analysis to identify areas for improvement in frontend performance and responsiveness, leading to increased user satisfaction",
        ],
        stack: ["css", "xhtml", "javascript", "jquery", "php"],
    },
    {
        position: "Frontend Developer",
        company: "MaxStyle",
        description: "Website agency",
        url: "https://www.maxstyle.ru",
        date: "10/2011 - 01/2012",
        achievements: [
            "Employed various technologies such as JavaScript, jQuery, Drupal, Joomla, XHTML, CSS, and PHP to create dynamic and interactive web applications",
            "Collaborated with cross-functional teams to ensure seamless integration between frontend and backend components",
            "Demonstrated expertise in creating responsive and visually appealing web designs, enhancing user experience across multiple devices and screen sizes",
        ],
        stack: [
            "css",
            "drupal",
            "javascript",
            "joomla",
            "jquery",
            "php",
            "xhtml",
        ],
    },
];
