import { TExperience } from "./types";

export const experiences: TExperience[] = [
    {
        position: "Contract Senior Front-end Engineer",
        company: "LeasePlan",
        url: "https://www.leaseplan.com",
        description:
            "One of the world's leading leasing companies, with 1.7 million vehicles in over 30 countries.",
        date: "08/2019 - present",
        achievements: [
            "As part of frontend ops and quality team helped devise and orchestrate move from monolith to microfrontends",
            "Contributed to holistic performance audit and improvement of leaseplan.com",
            "Took ownership, coordinated and delivered a valuable MVP business solution with very tight deadlines for fleet management of LP France",
            "Fully revamped and scaled integration of in-house generic sitecore form-library solution",
            "Improved build tools",
            "Improved front-end architecture",
            "Helped release in-house SiteCoreCMS form library",
        ],
        stack: [
            "auth0-react",
            "axios",
            "babel",
            "bem",
            "cypress",
            "datadog",
            "docker",
            "enzyme",
            "eslint",
            "express",
            "gitlab",
            "html5",
            "javascript",
            "jest",
            "k8s",
            "lodash",
            "material-ui",
            "mocha",
            "moment",
            "msw",
            "node",
            "prettier",
            "react",
            "react-final-form",
            "react-i18next",
            "react-router",
            "redux",
            "redux-saga",
            "reselect",
            "rollup",
            "scss",
            "sitecore",
            "sitecore-jss",
            "sitecore-jss-react",
            "standard-version",
            "storybook",
            "styled-components",
            "superagent",
            "testing-library",
            "tslint",
            "typescript",
            "webpack",
        ],
    },
    {
        position: "Senior Front-end Engineer",
        company: "Catawiki",
        url: "https://www.catawiki.com",
        description: "Europe's fastest growing online auction house",
        date: "02/2019 - 07/2019",
        achievements: [
            "Helped roll out mobile-first version of auction lot details page",
            "Improved build tools",
            "Improved front-end architecture",
        ],
        stack: [
            "ansible",
            "babel",
            "bem",
            "docker",
            "eslint",
            "express",
            "html5",
            "javascript",
            "node",
            "phoenix-css",
            "react",
            "redux",
            "redux-thunk",
            "scss",
            "shell",
            "tslint",
            "typescript",
            "webpack",
        ],
    },
    {
        position: "Senior Front-end Engineer",
        company: "IPsoft",
        url: "https://www.ipsoft.com",
        description:
            "Enterprise-scale autonomic and cognitive solutions platform, in use by 1 in 10 Fortune 1000 companies",
        date: "09/2017 - 11/2018",
        achievements: [
            "Extracted UI from monolith and moved it into a separated monorepo SPA architecture",
            "Migrated UI from ExtJS 4 to react 16 ecosystem",
            "Initiated and guided code style, architecture unification",
            "Introduced build tools to increase team efficiency and code quality",
            "Reduced time to first meaningful paint on all modules with best result: from 16s to 200ms",
        ],
        stack: [
            "angular",
            "babel",
            "bem",
            "d-3",
            "docker",
            "eslint",
            "express",
            "extjs4",
            "haproxy",
            "html5",
            "javascript",
            "maven",
            "node",
            "react",
            "redux",
            "redux-saga",
            "scss",
            "semantic-ui",
            "thymeleaf",
            "webpack",
            "xml",
            "xslt",
        ],
    },
    {
        position: "Front-end Engineer",
        company: "Casengo",
        description: "Customer support platform",
        url: "https://www.casengo.com",
        date: "06/2015 - 08/2017",
        achievements: [
            "Significantly decreased technical debt",
            "Significantly improved main app performance and stability",
            "Suggested and integrated solutions for UI scalability",
            "Made the app responsive for tablets and phones",
            "Improved chaotic CSS introducing BEM methodology",
            "Initiated business logic knowledge unification",
            "Developed a messenger bot from scratch that became one of the biggest chunks of company revenue",
        ],
        stack: [
            "angular",
            "atmosphere",
            "babel",
            "bem",
            "bootstrap",
            "eslint",
            "express",
            "extjs",
            "html5",
            "javascript",
            "mongodb",
            "mongoose",
            "node",
            "scss",
            "socket-io",
            "webpack",
        ],
    },
    {
        position: "Front-end Engineer",
        company: "Mail.Ru Group",
        url: "https://mail.ru",
        description:
            "Biggest russian e-mail service, 100mln accounts, 43.2 million active users/month",
        date: "08/2014 - 05/2015",
        achievements: [
            "Helped designing and implementing 2-step-auth integration",
            "Designed, implemented and integrated password recovery interface",
            "Designed, implemented and integrated emoji into email list and compose view",
            "Designed, implemented and integrated enhanced on-site testing functionality for end users",
            "Contributed to unification of in-house cross-project component toolkit",
        ],
        stack: [
            "bem-toolkit",
            "css3",
            "grunt",
            "html5",
            "javascript",
            "jquery",
            "jssdk",
            "require",
            "scss",
            "xml",
        ],
    },
    {
        position: "Freelance Front-end Engineer",
        company: "",
        description: "",
        url: "",
        date: "04/2014 - 08/2014",
        achievements: [
            "Redesigned an ecommerce website",
            "Built various landing pages",
        ],
        stack: ["css", "html", "javascript", "jquery"],
    },
    {
        position: "Front-end Engineer",
        company: "AdProfy",
        description: "Advertising platform",
        url: "http://adprofy.com",
        date: "04/2012 - 04/2014",
        achievements: [
            "Redesigned an ad platform",
            "Introduced BEM to improve style organization",
            "Built various side landing pages",
        ],
        stack: ["css", "xhtml", "javascript", "jquery", "php"],
    },
    {
        position: "Front-end Engineer",
        company: "MaxStyle",
        description: "Website agency",
        url: "https://www.maxstyle.ru",
        date: "10/2011 - 01/2012",
        achievements: ["Built widgets and landing pages"],
        stack: [
            "css",
            "drupal",
            "javascript",
            "joomla",
            "jquery",
            "php",
            "xhtml",
        ],
    },
];
